xcodeproj 'AeroGear-iOS.xcodeproj'

platform :ios, '5.0'

pod 'AFNetworking', '1.3.1'

target 'AeroGear-iOSTests', :exclusive => true do
    pod 'OCMock', '2.1.1'
    pod 'OHHTTPStubs', '1.1.2'
    pod 'Kiwi', '2.1'
end
